@startuml


actor "Administrator" as admin
boundary "Katagori Hukum Page" as katagori
boundary "AuthMiddleware" as middleware
control "CategoryController" as controller
entity "Model Category" as model

admin -[#Blue]> katagori : Request method GET
katagori -[#Blue]> middleware : Tambah katagori method POST
activate middleware
middleware -[#Red]> middleware : Autentication
middleware --[#Red]> katagori : Admin belum login
katagori --[#Red]> admin : Redirect to login method GET
middleware -[#Blue]> controller : Request diteruskan
deactivate middleware

activate controller
controller -[#Red]> controller : Validasi
controller --[#Red]> katagori : Response failed
katagori --[#Red]> admin : Response failed
controller -[#Blue]> model : Create katagori hukum
activate model
model --[#Green]> controller : Response success
deactivate model
controller --[#Green]> katagori : Response success
deactivate controller
katagori --[#Green]> admin : Tambah katagori hukum successfull
@enduml