@startuml

actor User as user
boundary "SISTEM JDIH" as sistem
control "Controller" as homeController
entity "Model Produk Hukum" as model
entity "Model Tipe Dokumen" as modeltipe

user -[#Blue]> sistem : Mengakses menu home
sistem -[#Blue]> homeController : Request method GET
activate homeController
homeController -[#Blue]> model : Get produk hukum
activate model
model --[#Green]> homeController : Data produk hukum
deactivate model
homeController -[#Blue]> modeltipe : Get tipe dokumen produk hukum
activate modeltipe
modeltipe --[#Green]> homeController : Data tipe dokumen
deactivate modeltipe
homeController -[#Blue]> model : Get produk hukum terbaru
activate model
model --[#Green]> homeController : Data produk hukum terbaru
deactivate model
homeController -[#Blue]> homeController : Menampilkan halaman home
homeController --[#Green]> sistem : Response success
deactivate homeController
sistem --[#Green]> user : Response success

group Fitur Halaman Home

    user -[#Blue]> sistem : Search produk hukum
    sistem -[#Blue]> homeController : Request method GET
    activate homeController
    homeController -[#Blue]> model : Get produk hukum
    activate model
    model --[#Green]> homeController : Data hasil pencarian
    deactivate model
    homeController -[#Blue]> homeController : Menampilkan hasil pencarian
    homeController --[#Green]> sistem : Response success
    deactivate homeController
    sistem --[#Green]> user : Response success

    user -[#Blue]> sistem : Mengakses produk hukum berdasarkan tipe dokumen
    sistem -[#Blue]> homeController : Request method GET
    activate homeController
    homeController -[#Blue]> modeltipe : Get produk hukum berdasarkan tipe dokumen
    activate modeltipe
    modeltipe --[#Green]> homeController : Data produk hukum berdasarkan tipe dokumen
    deactivate modeltipe
    homeController -[#Blue]> homeController : Menampilkan produk hukum berdasarkan tipe dokumen
    homeController --[#Green]> sistem : Response success
    deactivate homeController
    sistem --[#Green]> user : Response success

    user -[#Blue]> sistem : Mengakses produk hukum terbaru
    sistem -[#Blue]> homeController : Request method GET
    activate homeController
    homeController -[#Blue]> model : Get produk hukum terbaru
    activate model
    model --[#Green]> homeController : Data produk hukum terbaru
    deactivate model
    homeController -[#Blue]> homeController : Menampilkan produk hukum terbaru
    homeController --[#Green]> sistem : Response success
    deactivate homeController
    sistem --[#Green]> user : Response success

end

@enduml
