@startuml


actor User as user
boundary "SISTEM JDIH"  as sistem
control  "Controller" as jenisController
entity "Model Tipe Dokumen" as modeltipedokument
entity "Model Produk Hukum" as modelproduk




user -[#Blue]> sistem : User mengases menu jenis
sistem -[#Blue]> jenisController : Request method GET
activate jenisController
jenisController -[#Blue]> modeltipedokument : Get tipe dokumen
activate modeltipedokument
modeltipedokument --[#Green]> jenisController : Mendapatkan data tipe dokumen
deactivate modeltipedokument 
jenisController -[#Blue]> jenisController : Menampilkan data tipe dokumen
jenisController --[#Green]> sistem : Response success
deactivate jenisController
sistem --[#Green]> user : Response success

group Fitur Halaman Jenis


user -[#Blue]> sistem : Searach tipe dokumen
sistem -[#Blue]> jenisController : Request method GET
activate jenisController
jenisController -[#Blue]> modeltipedokument: Search tipe dokumen berdasarkan inputan 
activate modeltipedokument
modeltipedokument --[#Green]> jenisController : data hasil pencarian
deactivate modeltipedokument
jenisController -[#Blue]> jenisController : Menampilkan hasil pencarian
jenisController --[#Green]> sistem : Response success
deactivate jenisController
sistem --[#Green]> user : Response success



user -[#Blue]> sistem : Menampilkan produk hukum berdasarkan tipe dokumen
sistem -[#Blue]> jenisController : Request method GET
activate jenisController
jenisController -[#Blue]> modelproduk : Get produk hukum berdasarkan tipe dokumen
activate modelproduk 
modelproduk --[#Green]> jenisController : Mendapatkan produk hukum berdasrakan tipe dokumen
deactivate modelproduk
jenisController -[#Blue]> jenisController : Menampilkan produk hukum berdasarkan tipe dokumen
jenisController --[#Green]> sistem : Request success
deactivate jenisController
sistem --[#Green]>  user : Request success
end


@enduml
