@startuml

participant User

actor User as user
boundary "SISTEM JDIH"  as jdih
control  "Controller" as controller
entity "Model" as model
database "Database" as db


user -> jdih : mengases sistem jdih
jdih -> controller : request data  

user -> jdih : mencari produk hukum
jdih -> controller : masukan kata kunci


    ' activate model
    ' model -> db: Memeriksa kredensial di database
    ' activate db
    ' db --> model: Data ditemukan
    ' deactivate db





@enduml
