@startuml

|Admistrator|
start
:mengakses halaman 
abstrak peraturan;
|Sistem|
:menampilkan halaman 
abstrak peraturan;
|Admistrator|
repeat:halaman abstrak peraturan;
:mengelolah abstrak
 peraturan FMIPA;
fork
    :menambah abstrak
     peraturan;
fork again
    :menghapus abstrak 
    peraturan;
fork again
    :update abstrak 
    peraturan;

    |Sistem|
end fork
:validasi data abstrak produk;
 backward :mengirimkan pesan error
  ke halaman abstrak peraturan;
repeat  while (valid?) is (no) not (yes)
:menyimpan data 
abstrak peraturan;
:memperbaharui data
 abstrak peraturan;
stop
@enduml

