@startuml

|Admistrator|
start
:mengakses halaman 
katagori peraturan;
|Sistem|
:menampilkan halaman 
katagori peraturan;
|Admistrator|
repeat:halaman katagori peraturan;
:mengelolah 
katagori peraturan ;
fork
    :menambah 
    katagori peraturan;
fork again
    :menghapus 
    katagori peraturan;
fork again
    :update 
    katagori peraturan;
    |Sistem|
end fork
:validasi data 
katagori peraturan;
 backward :mengirimkan pesan error
  ke halaman 
  katagori peraturan;
repeat  while (valid?) is (no) not (yes)
:menyimpan data 
katagori peraturan;
:memperbaharui data 
katagori peraturan;
stop
@enduml

