@startuml

|Administrator|
start
:Mengakses halaman login;
    |Sistem|
repeat :menampilkan halaman login;
:request diteruskan ;
    |Administrator|
    :Memasukan username dan password;
    |Sistem|
    :validasi username dan password;
        backward :mengirimkan pesan
        username atau password salah;
repeat while (valid?) is (no) not (yes)
:Jika Username dan Password Valid,
maka akan dibuatkan session;
:Redirect ke halaman dashboard;
stop
@enduml

