@startuml

|Admistrator|
start
:Mengases Halaman JDIH FMIPA;
|Sistem|
:menampilkan halaman JDIH FMIPA;
|Admistrator|
:Login;
:memasukan username dan password;
|Sistem|
:masuk kehalaman admin;
|Admistrator|
:Mengelolah peraturan FMIPA
* create
* update
* delete;
|Sistem|
:data di perbarui;
|Admistrator|
:Logout;
|Sistem|
:keluar dari halaman admin;
stop
@enduml

