@startuml

|Admistrator|
start
:mengakses halaman 
tipe peraturan;
|Sistem|
:menampilkan halaman
 tipe peraturan;
|Admistrator|
repeat:halaman tipe peraturan;
:mengelolah tipe 
peraturan ;
fork
    :menambah tipe 
    peraturan;
fork again
    :menghapus tipe 
    peraturan;
fork again
    :update tipe 
    peraturan;
    |Sistem|
end fork
:validasi data
 tipe peraturan;
 backward :mengirimkan pesan error
  ke halaman tipe peraturan;
repeat  while (valid?) is (no) not (yes)
:menyimpan data 
tipe peraturan;
:memperbaharui 
data tipe peraturan;
stop
@enduml

