@startuml



class Category{
    id int(11) <<PK>>
    --
    title varchar(255)
    short_title varchar(255)
    slug varchar(255)
}

class ProductHukum{
    id int(11) <<PK>>
    category_hukum_id(11) <<FK>>
    produk_hukum_id (11) <<FK>>
    --
    nama_peraturan varchar (255)
    deskripsi varchar (255)
    judul varchar (255)
    tipe_document varchar(255)
    tahun varchar(255)
    tempat_penetapan varchar(255)
    tanggal_penetapan varchar(255)
    tanggal_pengundangan varchar(255)
    taggal_berlaku varchar(255)
    sumber varchar(255)
    subjek varchar (255)
    status enum("berlaku", "tidak berlaku")
    bahasa varchar (255)
    lokasi varchar (255)
    file varchar(255)
    bidang varchar (255)
    mengubah varchar(255)
    diubah varchar(255)
    mencabut varchar(255)
    dicabut varchar(255)
    slug varchar(255)
}


class SubjekProdukHukum{
    id int(11) <<PR>>
    subjek_id int(11) <<FK>>
    produk_id int(11) <<FK>>
}



class AbstrakHukum{
    id int(11) <<PK>>
    produk_hukum_id <<FK>>
    --
    title varchar(255)
    materi_pokok text()
    abstract text()
    catatan text()
    slug varchar(255)
}


ProductHukum}|--{Category
ProductHukum }|--{SubjekProdukHukum
SubjekHukum }|--{SubjekProdukHukum
ProductHukum }|--|{AbstrakHukum





@enduml