@startuml

|User|
start
:Mengases Halaman
JDIH FMIPA;
|Sistem|
:menampilkan halaman
JDIH FMIPA;
|User|
:Mencari peraturan;

:Memasukan kata kunci;
|User|
|Sistem|

:Mencari peraturan
berdasarkan kata kunci;
if (data ditemukan?) then (no) 
  :menampilan pesan 
  peraturan tidak ditemukan;
  stop
endif

|User|
:Memilih peraturan;
|Sistem|
:menampilan detail peraturan;
|User|
:melihat dokumen;
:mendownload dokumen;
stop
@enduml

