@startuml

actor Administrator as admin
boundary "Katagori Hukum Page" as katagori
boundary "Middleware" as middleware
control "Controller" as controller
entity "Model" as model

admin -> katagori : Mengakses kategori hukum
katagori -> middleware : Request

activate middleware
middleware -> katagori : Pengguna belum login
katagori --> admin : Tampilkan halaman login
deactivate middleware

admin -> katagori : Masukkan kredensial
katagori -> middleware : Request

activate middleware
middleware -> controller : Verifikasi kredensial
        
controller -> controller : validasi data
        
controller -> middleware : Kredensial valid
middleware -> katagori : Set sesi pengguna
katagori --> admin : Redirect ke halaman kategori hukum
deactivate middleware


admin -> katagori : Akses kategori hukum
katagori -> middleware : Request
activate middleware
middleware -> controller : Verifikasi sesi pengguna
controller -> model : Ambil data kategori hukum
model --> controller : Data kategori hukum
controller --> katagori : Data diterima
katagori --> admin : Tampilkan kategori hukum
deactivate middleware

@enduml
