@startuml

actor Administrator as admin
boundary "Login" as login
control "UserController" as controller
entity "Model User" as model

admin -[#Blue]> login : Admin Login

login -[#Blue]> controller: Request method GET

activate controller 
controller --[#Green]> login : Response success
deactivate controller
login --[#Green]> admin : Response success

admin -[#Blue]> login : Masukan username dan password
login -[#Blue]> controller : Request method POST


activate controller
controller -[#Red]> controller: Validasi Data
controller --[#Red]> login : Response failed
login --[#Red]> admin : Response failed

alt Data Valid 
    controller -[#Blue]> model: Get data user
    activate model
    model --[#Green]> controller: Response success
    deactivate model
    controller -[#Green]> controller : Mendapatkan data user membuat sessions
    controller --[#Green]> login: Response success
    login --[#Green]> admin: Redirect ke dashboard method GET
    
else Data Tidak Valid
    controller --[#Red]> login: Response gagal
    deactivate controller
    login --[#Red]> admin: Username atau password salah
    deactivate controller
end

@enduml
