@startuml

actor Administrator as admin
boundary "Logout" as logout
boundary "AuthMiddleware" as middleware
control "Controller" as controller
entity "Model" as model

admin -[#Blue]> logout : Admin logout
logout -[#Blue]> middleware : Request method GET
activate  middleware
middleware -[#Red]> middleware : Authentication
middleware --[#Red]> logout : Response failed
logout --[#Red]> admin : Redirect to login method GET
middleware -[#Blue]> controller : Request diteruskan
deactivate middleware
activate controller
controller -[#Blue]> controller: Melakukan proses logout
controller -[#Blue]> model: Menghapus data session
controller --[#Green]> logout: Response success
deactivate controller

logout --[#Green]> admin: Redirect to login method GET

@enduml
