@startuml


left to right direction

:Administrator: as  admin
:User : as user

package "Sistem JDIH FMIPA" {

    usecase "Login" as login
    usecase "Logout" as logout
    usecase "Peraturan" as peraturan
    usecase "Tahun Peraturan" as tahunPeraturan
    usecase "Subjek Peraturan" as subjekPeraturan
    usecase "Tipe Peraturan" as tipePeraturan
    usecase "Katagori Peraturan" as katagoriPeraturan
    usecase "Abstrak Peraturan" as abstrakPeraturan
    usecase "Mengelolah" as mengelolah

    usecase "Download Dokumen" as downloadDokumen
    usecase "Melihat Dokumen" as melihatDokumen
    usecase "Produk Hukum" as produkHukum
    usecase "Mencari peraturan" as mencariPeraturan
}




admin --> mengelolah
admin --> login
admin --> logout
login  ..> logout : <<include>>
mengelolah <.. abstrakPeraturan: <<extend>>
mengelolah <.. subjekPeraturan: <<extend>>
mengelolah <.. tipePeraturan: <<extend>>
mengelolah <.. katagoriPeraturan: <<extend>>
mengelolah <.. peraturan: <<extend>>
mengelolah <.. tahunPeraturan: <<extend>>
mengelolah ..> login: <<include>>
mengelolah ..> peraturan : <<include>>



peraturan <.. tahunPeraturan : <<extend>>
peraturan <.. abstrakPeraturan : <<extend>>
peraturan <.. subjekPeraturan : <<extend>>
peraturan <.. tipePeraturan : <<extend>>
peraturan <.. katagoriPeraturan : <<extend>>
peraturan  ..> produkHukum : <<include>>


produkHukum .. mencariPeraturan : <<extend>>
produkHukum .. downloadDokumen : <<extend>>
produkHukum .. melihatDokumen : <<extend>>

user --> downloadDokumen
user --> melihatDokumen
user --> produkHukum
user --> mencariPeraturan

@enduml