@startuml


actor "Administrator" as admin
boundary "Tipe Dokumen Page" as Tipe
boundary "AuthMiddleware" as middleware
control "TipeDocumentController" as controller
entity "TipeDokumen Model" as model
' database "Database" as db

loop View Tipe Dokumen 
    admin -[#Blue]> Tipe : Menampilkan Tipe Dokument
    ' note left: admin mengases Tipe Dokumen
    Tipe -[#Blue]> middleware: Request method GET 
    activate middleware
            middleware -[#Red]> middleware: authentication
            middleware --[#Red]> Tipe : Admin belum login
            Tipe --[#Red]> admin : redirect to login method GET
            middleware -[#Blue]> controller : Request diteruskan
    deactivate middleware
            activate controller
                controller -[#Blue]> model : Get data Tipe Dokument
                    activate model
                    model --[#Green]> controller : Response  sukses
                    deactivate model
                    controller --[#Green]> Tipe : Response  sukses
            deactivate controller
                Tipe --[#Green]> admin : Menampilkan Data Tipe Dokumen


        ' DELETE
        group Delete Tipe Dokumen
            admin -[#Blue]> Tipe : Request method GET
            ' note left: admin mengases Tipe Dokumen

            Tipe -[#Blue]> middleware: Delete Tipe Dokumen by id

       activate middleware
            middleware -[#Red]> middleware: authentication
            middleware --[#Red]> Tipe : Admin belum login
            Tipe --[#Red]> admin : redirect to login method GET
            middleware -[#Blue]> controller : Request diteruskan
        deactivate middleware
            activate controller
            controller -[#Blue]> model : Delete data Tipe Dokumen
            activate model
            model --[#Green]> controller : Response  sukses
            deactivate model
            controller --[#Green]> Tipe : Response  sukses
            deactivate controller
            Tipe --[#Green]> admin : Tipe Dokumen delete succesfull
        end


        ' UPDATE
        group Update Tipe Dokumen
            admin -[#Blue]> Tipe : Get Tipe Dokumen by id
            ' note left: admin mengases Tipe Dokumen

            Tipe -[#Blue]> middleware:  Request method GET
        activate middleware
            middleware -[#Red]> middleware: authentication
            middleware --[#Red]> Tipe : Admin belum login
            Tipe --[#Red]> admin : redirect to login method GET
            middleware -[#Blue]> controller : Request diteruskan
        deactivate middleware
            activate controller
            controller -[#Blue]> model : Get data Tipe Dokumen
            activate model
            model --[#Green]> controller : Response  sukses
            deactivate model
            controller --[#Green]> Tipe : Response  sukses
            deactivate controller
                Tipe --[#Green]> admin : Menampilkan Data Tipe Dokumen
            
             admin -[#Blue]> Tipe : Update Tipe Dokumen by id
            activate Tipe
             Tipe -[#Blue]> middleware : Request method POST
            deactivate Tipe
            activate middleware
             middleware -[#Red]> middleware : authentication
            middleware --[#Red]> Tipe : Admin belum login
            Tipe --[#Red]> admin : redirect to login method GET

            middleware -[#Blue]> controller : Request diteruskan
            deactivate middleware
            activate controller
            controller -[#Red]> controller : Validasi
            controller --[#Red]> Tipe : Response  failed
            Tipe --[#Red]> admin : Response  failed
            controller -[#Blue]> model : Update Tipe Dokumen
            activate model 
            model --[#Green]> controller : Response  sukses
            deactivate model
            controller --[#Green]> Tipe : Response sukses
            Tipe --[#Green]> admin : Tipe Dokumen update succesfull
            deactivate controller
            
        end


end


@enduml